name: Laravel CD

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Laravel CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Debug Docker Config
        run: cat ~/.docker/config.json

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcr:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcr:${{ github.sha }}

      - name: Clear Laravel Cache
        run: |
          docker run --rm \
            -e DB_CONNECTION=mysql \
            -e DB_HOST=${{ secrets.CLOUD_SQL_HOST }} \
            -e DB_PORT=3306 \
            -e DB_DATABASE=fp_pso \
            -e DB_USERNAME=root \
            -e DB_PASSWORD='' \
            -e APP_KEY=${{ secrets.APP_KEY }} \
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcr:${{ github.sha }} \
            php artisan config:clear

      - name: Test Database Connection
        run: |
          docker run --rm \
            -e DB_CONNECTION=mysql \
            -e DB_HOST=${{ secrets.CLOUD_SQL_HOST }} \
            -e DB_PORT=3306 \
            -e DB_DATABASE=fp_pso \
            -e DB_USERNAME=root \
            -e DB_PASSWORD='' \
            -e APP_KEY=${{ secrets.APP_KEY }} \
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcr:${{ github.sha }} \
            php artisan tinker --execute="DB::connection()->getPdo(); echo 'Connection successful';"

      - name: Run Database Migrations
        run: |
          docker run --rm \
            -e DB_CONNECTION=mysql \
            -e DB_HOST=${{ secrets.CLOUD_SQL_HOST }} \
            -e DB_PORT=3306 \
            -e DB_DATABASE=fp_pso \
            -e DB_USERNAME=root \
            -e DB_PASSWORD='' \
            -e APP_KEY=${{ secrets.APP_KEY }} \
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcr:${{ github.sha }} \
            php artisan migrate --force

      - name: Verify File Permissions
        run: |
          docker run --rm \
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcr:${{ github.sha }} \
            ls -ld /var/www/html/storage /var/www/html/bootstrap/cache

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hrms-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcr:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --service-account hrms-deployment@feisty-reality-461020-d5.iam.gserviceaccount.com \
            --set-env-vars "APP_ENV=production,APP_DEBUG=true,APP_KEY=${{ secrets.APP_KEY }},DB_CONNECTION=mysql,DB_HOST=${{ secrets.CLOUD_SQL_HOST }},DB_PORT=3306,DB_DATABASE=fp_pso,DB_USERNAME=root,DB_PASSWORD=,APP_LOG_CHANNEL=stack" \
            --timeout 600 \
            --memory 512Mi \
            --cpu 1 \
            --allow-unauthenticated \
            --quiet
